name: Hello World Workflow
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello World!"

    - name: Print date and time
      run: date

    - name: List directory
      run: ls -ltr
