name: Deployment pipeline
on:
  push:
    branches:
      - main
  pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Install
        run: npm install  
      - name: Install dependencies
        run: npm ci
      - name: Fix warnings 
        run: npm audit fix
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Lint
        run: npm run eslint -- --fix
      - name: Build
        run: npm run build
      - name: Test - unit tests 
        run: npm test 
      - name: Test - e2e tests
        run: npx playwright test
      - name: Fly.io - flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        if: ${{ github.event_name == 'push' }} && ${{ !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') }}
        run: flyctl deploy --remote-only
        env:
            FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
      - name: Build success
        uses: tsickert/discord-webhook@v6.0.0 
        if: success()
        with: 
            username: ${{ github.event.head_commit.author.name }}
            content: Info - A new version of application deployed by ${{github.event.head_commit.author.name}}
            webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
    
      - name: Build failed
        uses: tsickert/discord-webhook@v6.0.0
        if: failure()
        with: 
            username: ${{ github.event.head_commit.committer.username }}
            content: Error - A build failed, commit ${{github.event.head_commit.url}} by ${{github.event.head_commit.author.name}} broke the build 
            webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }} && ${{ !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
    


