name: Deployment pipeline
on:
  push:
    branches:
      - main
  pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Install
        run: npm install  
      - name: Install dependencies
        run: npm ci
      - name: Fix warnings 
        run: npm audit fix
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Lint
        run: npm run eslint -- --fix
      - name: Build
        run: npm run build
      - name: Test - unit tests 
        run: npm test 
      - name: Test - e2e tests
        run: npx playwright test
      - name: Fly.io - flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
            FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
    


