on:
    schedule:
        - cron: "0 * * * *"
jobs:
    url_check:
        runs-on: ubuntu-20.04
        steps:
          - name: Ping URL
            uses: jtalk/url-health-check-action@v4
            with:
                url:  ${{ vars.HEALTH_CHECK_URL }}
          - name: failure
            uses: rjstone/discord-webhook-notify@v1.0.4
            if: failure()
            with: 
                severity: error
                description: URL health check failed 
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}