name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    if: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        if: ${{ !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') }}
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), ' ') }}
        run: echo "$COMMIT_MESSAGES"

      - name: success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with: 
            username: ${{ github.event.head_commit.author.name }}
            severity: info
            description: A new version deployed 
            details: A new version of application deployed by ${{github.event.head_commit.author.name}}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with: 
            username: ${{ github.event.head_commit.committer.username }}
            severity: error
            description: A build failed
            details: Commit ${{github.event.head_commit.url}} by ${{github.event.head_commit.author.name}} broke the build 
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  url_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Ping URL
        uses: jtalk/url-health-check-action@v4
        with:
        # Check the following URLs one by one sequentially
            url:  ${{ vars.HEALTH_CHECK_URL }}
      - name: failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with: 
            severity: error
            description: URL health check failed 
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
