name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        if: ${{ !contains(join(toJson(github.event.commits.*.message), ' '), '#skip') }}
        env:
          COMMIT_MESSAGES: ${{ join(toJson(github.event.commits.*.message), ' ') }}
        run: echo "$COMMIT_MESSAGES"
      - name: success
        uses: rjstone/discord-webhook-notify@v1
        if: {{ success() }}
        with: 
            username: ${{ github.event.head_commit.committer.username }}
            severity: info
            description: A new version deployed 
            details: ${{"A new version of application deployed by "}}${{github.event.head_commit.committer.username}}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: success
        uses: rjstone/discord-webhook-notify@v1
        if: {{ success() }}
        with: 
            username: ${{ github.event.head_commit.committer.username }}
            severity: error
            description: A build failed
            details: ${{"Commit " github.event.head_commit.url}}${{" by "}}${{github.event.head_commit.committer.username}}${{" broke the build"}}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

